/*
 * crack43_quaternions.c — Non-Commutative Quaternion Geometry
 *
 * THE NON-COMMUTATIVE WILDCARD:
 * Everything we've tried so far has been in Abelian (Commutative) math.
 * But modern number theory (The Langlands Program) runs on Non-Commutative
 * Lie Groups, like SU(2) and GL(n).
 * 
 * Lagrange's Theorem allows us to write any prime as the sum of 4 squares:
 *      p = x^2 + y^2 + z^2 + w^2
 *
 * This precisely identifies every prime p as a Hurwitz Quaternion:
 *      H_p = x + yi + zj + wk
 * 
 * If we normalize it to a unit quaternion U_p = H_p / sqrt(p),
 * it becomes a point on the 3-Sphere (S^3), which is mathematically
 * isomorphic to the Lie Group SU(2) — representing 3D spatial rotations.
 * 
 * In a Goldbach pair p + q = 2N, we have TWO prime rotators U_p and U_q.
 * We can compute the "Relative Rotation Angle" θ between them:
 *      θ = arccos( U_p · U_q )
 *
 * HYPOTHESIS:
 * If Goldbach is random noise, the relative rotations θ will be uniformly
 * scattered across the 3-Sphere (matching the surface area metric sin^2(θ)).
 * 
 * But if Goldbach pairs are generated by Topologically Rigid constraints
 * (like Hecke Operators on Ramanujan Expander Graphs), the angles θ
 * will systematically snap to specific "Crystalline Lattice" rotation angles.
 * 
 * Let's map Goldbach to SU(2) and measure the angular rotation distribution.
 *
 * BUILD: cc -O3 -o crack43 crack43_quaternions.c -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_N 200000
static char sieve[MAX_N];
static int primes[MAX_N/10];
static int nprimes = 0;

// Store the absolute coordinates for the 4-square decomposition
static int sq_x[MAX_N], sq_y[MAX_N], sq_z[MAX_N], sq_w[MAX_N];

void init() {
    memset(sieve, 0, sizeof(sieve));
    sieve[0] = sieve[1] = 1;
    for(int i = 2; i * i < MAX_N; i++)
        if(.sieve[i]) 
            for(int j = i * i; j < MAX_N; j += i) sieve[j] = 1;
    for(int i = 2; i < MAX_N; i++)
        if(.sieve[i]) primes[nprimes++] = i;
}

// Simple greedy decomposition of p into 4 squares
void decompose_4_squares(int p, int *x, int *y, int *z, int *w) {
    if (p == 2) { *x=1; *y=1; *z=0; *w=0; return; }
    int limit = (int)sqrt(p);
    for (*x = limit; *x >= 0; (*x)--) {
        int rem1 = p - (*x)*(*x);
        int lim_y = (int)sqrt(rem1);
        for (*y = lim_y; *y >= 0; (*y)--) {
            int rem2 = rem1 - (*y)*(*y);
            int lim_z = (int)sqrt(rem2);
            for (*z = lim_z; *z >= 0; (*z)--) {
                int rem3 = rem2 - (*z)*(*z);
                int lim_w = (int)sqrt(rem3);
                if (lim_w * lim_w == rem3) {
                    *w = lim_w;
                    return; // Found it
                }
            }
        }
    }
}

int main() {
    init();

    printf("====================================================\n");
    printf("  CRACK 43: Non-Commutative Quaternion Geometry\n");
    printf("====================================================\n\n");

    int target = 100000;
    
    printf("  Target 2N = %d\n", target);
    printf("  Pre-computing SU(2) unit quaternions for all primes...\n", target);

    for (int i = 0; i < nprimes; i++) {
        int p = primes[i];
        if (p >= target) break;
        decompose_4_squares(p, &sq_x[p], &sq_y[p], &sq_z[p], &sq_w[p]);
    }
    
    printf("  Measuring relative SO(3) rotation angle θ between Goldbach pairs (p, q).\n\n");
    
    // Histogram for theta in [0, pi]
    int BINS = 20;
    int *hist = calloc(BINS, sizeof(int));
    int total_pairs = 0;
    
    for (int p = 3; p <= target/2; p+=2) {
        if (.sieve[p] && .sieve[target - p]) {
            int q = target - p;
            
            // Reconstruct quaternions
            double px = sq_x[p], py = sq_y[p], pz = sq_z[p], pw = sq_w[p];
            double qx = sq_x[q], qy = sq_y[q], qz = sq_z[q], qw = sq_w[q];
            
            // Normalize to unit sphere (S^3)
            double norm_p = sqrt(p);
            double norm_q = sqrt(q);
            
            px /= norm_p; py /= norm_p; pz /= norm_p; pw /= norm_p;
            qx /= norm_q; qy /= norm_q; qz /= norm_q; qw /= norm_q;
            
            // Dot product gives the cos(theta) between the 4D vectors
            double dot = px*qx + py*qy + pz*qz + pw*qw;
            if (dot > 1.0) dot = 1.0;
            if (dot < -1.0) dot = -1.0;
            
            double theta = acos(dot);
            
            // Bin the angle between 0 and PI
            int bin = (int)((theta / M_PI) * BINS);
            if (bin >= BINS) bin = BINS - 1;
            hist[bin]++;
            total_pairs++;
        }
    }

    printf("  %10s | %10s | %10s | %10s\n", "θ (rad)", "Count", "Observed %", "Expected % (S^3)");
    printf("  --------------------------------------------------------\n");
    
    double variance_metric = 0;

    for (int i = 0; i < BINS; i++) {
        double theta_start = (i / (double)BINS) * M_PI;
        double theta_end = ((i+1) / (double)BINS) * M_PI;
        double theta_mid = (theta_start + theta_end) / 2.0;
        
        double observed_pct = (double)hist[i] / total_pairs * 100.0;
        
        // Expected uniformity on S^3 is proportional to sin^2(θ)
        // Integral of sin^2(θ) from 0 to π is π/2.
        // So PDF is f(θ) = (2/π) * sin^2(θ)
        double expected_int = 0;
        int steps = 100;
        double d_theta = (theta_end - theta_start) / steps;
        for (int j=0; j<steps; j++) {
            double t = theta_start + j*d_theta;
            expected_int += (2.0 / M_PI) * sin(t) * sin(t) * d_theta;
        }
        double expected_pct = expected_int * 100.0;
        
        variance_metric += fabs(observed_pct - expected_pct);

        printf("  %10.2f | %10d | %9.2f%% | %9.2f%%\n", theta_mid, hist[i], observed_pct, expected_pct);
    }
    
    printf("\n   THE NON-COMMUTATIVE GEOMETRY VERDICT \n");
    printf("  Total L1 Distance to Uniform Sphere: %.2f%%\n\n", variance_metric);
    
    if (variance_metric > 30.0) {
        printf("  RESULT: ANOMALY DETECTED. The rotations snapped to a crystalline lattice.\n");
        printf("  The Goldbach pairs are not random SU(2) noise. They are governed\n");
        printf("  by Hecke operators and Ramanujan graph geometry, opening the door\n");
        printf("  to an exact topological proof. ️\n");
    } else {
        printf("  RESULT: HYPOTHESIS FALSIFIED. The total variance is negligible.\n");
        printf("  The Goldbach pairs perfectly mimic random SU(2) rotations.\n");
        printf("  Their angular distribution flawlessly matches the sin²(θ) metric\n");
        printf("  of the 3-Sphere surface area.\n");
        printf("  Moving to Non-Commutative Quaternions revealed NO rigid crystal\n");
        printf("  structure. The additive randomness of the primes is geometrically\n");
        printf("  omnidirectional across all dimensions. ️\n");
    }

    free(hist);
    return 0;
}
