/*
 * crack48_tropical_geometry.c — Tropical Geometry & Min-Plus Algebra
 *
 * THE TROPICAL SEMIRING:
 * We abandon classical Field arithmetic (+, *) and enter the Tropical
 * Semiring (R ∪ {∞}, ⊕, ⊗).
 * 
 * Tropical Addition:      x ⊕ y = min(x, y)
 * Tropical Multiplication: x ⊗ y = x + y
 *
 * This profound transformation "dequantizes" algebraic geometry. Smooth curves
 * become piecewise-linear graphs consisting of straight lines and vertices
 * (called Tropical Amoebas).
 *
 * A "Tropical Polynomial" P(x) = a ⊗ x² ⊕ b ⊗ x ⊕ c becomes:
 * P(x) = min(a + 2x, b + x, c)
 * 
 * The "roots" of a tropical polynomial are the points x where the minimum
 * is achieved by AT LEAST TWO terms simultaneously (causing a sharp vertex,
 * or non-differentiability, in the piecewise-linear graph).
 *
 * THE TROPICAL GOLDBACH GEOMETRY:
 * We map the primes into a Tropical Polynomial.
 * We define P_2N(x) = min_{p < 2N} [ p ⊗ x^(2N - p) ]
 * Which translates to:
 * P_2N(x) = min_{p < 2N} [ p + (2N - p)x ]
 *
 * This generates an explicitly linear arrangement of lines in the 2D plane.
 * A vertex (a tropical root) occurs when two lines intersect and form the minimum.
 * 
 * If Goldbach is algebraically structured under Tropical transformation,
 * the vertices of P_2N(x) will precisely isolate the exact Goldbach prime pairs p, q.
 * 
 * Let's construct the piecewise-linear Tropical Amoeba and identify its roots.
 *
 * BUILD: cc -O3 -o crack48 crack48_tropical_geometry.c -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_N 200000
static char sieve[MAX_N];
static int primes[MAX_N];
static int nprimes = 0;

void init() {
    memset(sieve, 0, sizeof(sieve));
    sieve[0] = sieve[1] = 1;
    for (int i=2; i*i < MAX_N; i++)
        if (.sieve[i]) 
            for (int j=i*i; j < MAX_N; j+=i) sieve[j] = 1;
    
    for (int i=2; i < MAX_N; i++)
        if (.sieve[i]) primes[nprimes++] = i;
}

// Represents a tropical term: a_i + b_i * x
typedef struct {
    double a;  // y-intercept (the prime p)
    double b;  // slope (2N - p)
    int p;     // the original prime
} Line;

int main() {
    init();

    printf("====================================================\n");
    printf("  CRACK 48: Tropical Geometry (Min-Plus Algebra)\n");
    printf("====================================================\n\n");

    int target = 20000;
    
    printf("  Target 2N = %d\n", target);
    printf("  Constructing Tropical Polynomial P(x) = ⊕_{p<2N} (p ⊗ x^(2N-p))\n");
    printf("  Translating to: P(x) = min_{p} [ p + (2N - p) * x ]\n\n");

    // Gather all lines generated by primes
    int num_lines = 0;
    for (int i=0; i<nprimes; i++) {
        if (primes[i] >= target) break;
        num_lines++;
    }
    
    Line *lines = malloc(num_lines * sizeof(Line));
    for (int i=0; i<num_lines; i++) {
        lines[i].p = primes[i];
        lines[i].a = primes[i];
        lines[i].b = target - primes[i];
    }
    
    printf("  Scanning the X-axis to identify Tropical Roots (Vertices)...\n");
    printf("  A root occurs when two lines intersect to form the lowest boundary.\n\n");
    
    printf("  %10s | %18s | %s\n", "Root X", "Intersecting p, q", "Is it Goldbach?");
    printf("  --------------------------------------------------------------\n");

    // We scan x from 0.0 to 2.0.
    // The lowest envelope of lines is a concave polygon.
    // The roots are the x-coordinates of the vertices.
    
    int current_min_idx = -1;
    int root_count = 0;
    int goldbach_roots = 0;
    
    // Fine-grained scan to detect slope changes (vertices)
    double step = 0.0001;
    for (double x = 0.0; x <= 2.0; x += step) {
        
        double min_val = 1e12;
        int min_idx = -1;
        
        for (int i=0; i<num_lines; i++) {
            double val = lines[i].a + lines[i].b * x;
            if (val < min_val) {
                min_val = val;
                min_idx = i;
            }
        }
        
        if (current_min_idx .= -1 && current_min_idx .= min_idx) {
            // A vertex occurred. The active minimum line changed.
            // The two primes responsible for this vertex are the previous and the new line.
            int p1 = lines[current_min_idx].p;
            int p2 = lines[min_idx].p;
            
            // Exactly calculate intersection X:
            // a1 + b1*X = a2 + b2*X  => X = (a1 - a2) / (b2 - b1)
            double exact_x = (lines[current_min_idx].a - lines[min_idx].a) / 
                             (lines[min_idx].b - lines[current_min_idx].b);
                             
            int is_gb = (p1 + p2 == target);
            if (is_gb) goldbach_roots++;
            root_count++;
            
            if (root_count <= 10) { // print first 10
                printf("  %10.4f | %6d, %8d | %s\n", exact_x, p1, p2, is_gb ? "YES " : "NO  ");
            }
        }
        
        current_min_idx = min_idx;
    }
    
    if (root_count > 10) printf("  ... (and %d more roots)\n", root_count - 10);

    double percentage = (root_count > 0) ? ((double)goldbach_roots / root_count) * 100.0 : 0.0;

    printf("\n   TROPICAL GEOMETRY VERDICT \n");
    printf("  Total Tropical Roots: %d\n", root_count);
    printf("  Goldbach Intersection Vectors: %d (%.2f%%)\n\n", goldbach_roots, percentage);
    
    if (percentage > 50.0) {
        printf("  RESULT: ANOMALY DETECTED. The lower hull physically mapped Goldbach combinations.\n");
        printf("  The non-Archimedean amoeba geometry correctly bound the primes. ️\n");
    } else {
        printf("  RESULT: HYPOTHESIS FALSIFIED. The piece-wise convex hull generated completely unrelated pairs.\n");
        printf("  Tropical Intersection roots are natively defined as X = (p1-p2)/(p1-p2) = 1.0.\n");
        printf("  Algebraically, ALL lines intersect at X=1.0. The lower envelope is just\n");
        printf("  finding adjacent primes near the target boundary.\n");
        printf("  By switching to Min-Plus algebra, we fundamentally destroyed the\n");
        printf("  Arithmetic Addition constraint p+q=2N. Min-Plus topology is blind to Goldbach. ️\n");
    }

    free(lines);
    return 0;
}
