/*
 * crack49_galois_frobenius.c — Galois Theory & Cyclotomic Fields
 *
 * THE CYCLOTOMIC GALOIS GROUP:
 * We move away from raw analytic geometry and into strict Field Theory.
 * Consider the 2N-th Cyclotomic Field Q(ζ_2N), where ζ is a primitive 
 * 2N-th root of unity.
 * 
 * The Galois Group G = Gal(Q(ζ_2N) / Q) is isomorphic to the multiplicative 
 * group of integers modulo 2N: (Z/2NZ)^x.
 * 
 * THE FROBENIUS AUTOMORPHISM:
 * For every prime p not dividing 2N, there is a distinct Frobenius element
 * in the Galois group: σ_p(ζ) = ζ^p.
 * 
 * The Chebotarev Density Theorem states that these Frobenius elements are 
 * uniformly distributed across the conjugacy classes of G.
 *
 * GOLDBACH AS A GALOIS SYMMETRY:
 * The additive Goldbach equation p+q=2N trivially implies p ≡ -q (mod 2N).
 * In the Galois Group, this multiplicative mapping becomes incredibly strict:
 *      σ_p = σ_{-q} = σ_{-1} ◦ σ_q^{-1}
 * 
 * The element σ_{-1} is Complex Conjugation. 
 * A Goldbach pair thus requires finding a prime p such that its Frobenius 
 * automorphism is explicitly the complex conjugate of the inverse of another 
 * prime's Frobenius automorphism.
 *
 * THE SUBGROUP TEST:
 * If Goldbach is algebraically constrained by the Field Extension, the Goldbach 
 * pairs (p, q) will heavily cluster into specific subgroups of (Z/2NZ)^x.
 * We will map the Frobenius elements into the group and measure their variance 
 * across the Subgroup generated by {σ_p}. 
 * If the Chebotarev density collapses, Field Theory governs Goldbach.
 *
 * BUILD: cc -O3 -o crack49 crack49_galois_frobenius.c -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_N 200000
static char sieve[MAX_N];
static int primes[MAX_N];
static int nprimes = 0;

int gcd(int a, int b) {
    while (b) {
        int t = b;
        b = a % b;
        a = t;
    }
    return a;
}

void init() {
    memset(sieve, 0, sizeof(sieve));
    sieve[0] = sieve[1] = 1;
    for (int i=2; i*i < MAX_N; i++)
        if (.sieve[i]) 
            for (int j=i*i; j < MAX_N; j+=i) sieve[j] = 1;
    
    for (int i=2; i < MAX_N; i++)
        if (.sieve[i]) primes[nprimes++] = i;
}

int main() {
    init();

    printf("====================================================\n");
    printf("  CRACK 49: Galois Theory (Frobenius Automorphisms)\n");
    printf("====================================================\n\n");

    int target_2N = 60000;
    
    printf("  Target 2N = %d. Extracting the Galois Group Gal(Q(ζ_2N) / Q).\n", target_2N);
    printf("  Group Order (Euler Totient φ(2N))...\n");

    int phi = 0;
    int *galois_elements = malloc(target_2N * sizeof(int));
    memset(galois_elements, 0, target_2N * sizeof(int));
    
    for (int i=1; i<target_2N; i++) {
        if (gcd(i, target_2N) == 1) {
            galois_elements[i] = 1;
            phi++;
        }
    }
    printf("  φ(%d) = %d total automorphisms.\n\n", target_2N, phi);

    // Track the Chebotarev density of Goldbach Frobenius elements vs Random primes
    int *gb_density = calloc(target_2N, sizeof(int));
    int gb_count = 0;
    
    int *random_density = calloc(target_2N, sizeof(int));
    int rand_count = 0;

    printf("  Evaluating σ_p = σ_{-1} ◦ σ_q^{-1} across the Subgroups...\n");

    for (int p=3; p<=target_2N/2; p+=2) {
        if (.sieve[p] && .sieve[target_2N - p]) {
            int q = target_2N - p;
            
            // Both p and q must be coprime to 2N to be in the Galois Group
            if (gcd(p, target_2N) == 1 && gcd(q, target_2N) == 1) {
                // p is an automorphism evaluated at p (mod 2N)
                // We tally the Frobenius density
                gb_density[p]++;
                gb_density[q]++;
                gb_count += 2;
            }
        }
    }
    
    // Generate an equivalent count of random primes that belong to the Galois group
    while (rand_count < gb_count) {
        int p = primes[rand() % nprimes];
        if (p < target_2N && gcd(p, target_2N) == 1) {
            random_density[p]++;
            rand_count++;
        }
    }

    // Measure Variance from uniform distribution
    double expected = (double)gb_count / phi;
    double gb_variance = 0;
    double rand_variance = 0;

    // Optional: measure Quadratic Residue density constraint (Subgroup of squares)
    int gb_squares = 0;
    int rand_squares = 0;
    int total_squares = 0;

    for (int i=1; i<target_2N; i++) {
        if (galois_elements[i]) {
            double diff_gb = gb_density[i] - expected;
            gb_variance += diff_gb * diff_gb;
            
            double diff_rand = random_density[i] - expected;
            rand_variance += diff_rand * diff_rand;
            
            // Is it a quadratic residue? (just a rough subgroup heuristic)
            // If i = x^2 (mod 2N). To properly check, we could evaluate Legendre, 
            // but we'll just pre-compute the squares mod 2N.
        }
    }
    
    // Precompute Squares
    int *is_square = calloc(target_2N, sizeof(int));
    for (int i=1; i<target_2N; i++) {
        if (galois_elements[i]) {
            long long sq = (long long)i * i;
            is_square[sq % target_2N] = 1;
        }
    }
    
    for (int i=1; i<target_2N; i++) {
        if (galois_elements[i] && is_square[i]) {
            total_squares++;
            gb_squares += gb_density[i];
            rand_squares += random_density[i];
        }
    }

    gb_variance /= phi;
    rand_variance /= phi;
    
    double square_subgroup_ratio = (double)total_squares / phi;

    printf("  %20s | %15s | %18s\n", "Galois Metric", "Goldbach σ_p", "Random σ_p");
    printf("  ------------------------------------------------------------------\n");
    printf("  %20s | %15.4f | %18.4f\n", "Chebotarev Variance", gb_variance, rand_variance);
    printf("  %20s | %14.2f%% | %17.2f%%\n", "Subgroup G^2 Density", 
        (double)gb_squares / gb_count * 100.0, 
        (double)rand_squares / rand_count * 100.0);
    printf("  %20s | %14.2f%% | %17.2f%%\n", "(Expected G^2)", 
        square_subgroup_ratio * 100.0, 
        square_subgroup_ratio * 100.0);

    printf("\n   GALOIS THEORY VERDICT \n");
    if (gb_variance > rand_variance * 5.0) {
        printf("  RESULT: ANOMALY DETECTED. The Goldbach Frobenius elements heavily clustered.\n");
        printf("  The huge Chebotarev variance proves Goldbach pairs are algebraically\n");
        printf("  locked into specific Galois Subgroups. Field Theory holds the key. ️\n");
    } else {
        printf("  RESULT: HYPOTHESIS FALSIFIED. The Frobenius automorphisms matched perfectly.\n");
        printf("  The Goldbach elements distribute across the Cyclic Field conjugacy classes\n");
        printf("  with the exact same uniform density as completely random primes.\n");
        printf("  The sum constraint p+q=2N has absolutely ZERO field-theoretic restriction\n");
        printf("  on the subgroups of Gal(Q(ζ_2N) / Q). The Frobenius elements are uniform. ️\n");
    }

    free(galois_elements); free(gb_density); free(random_density); free(is_square);
    return 0;
}
