/*
 * crack67_machine_learning.c — Artificial Intelligence (DNN Gradient Covergence)
 *
 * THE CONTINUOUS NEURAL MANIFOLD:
 * In Deep Learning, Neural Networks construct massive, continuous, 
 * high-dimensional mathematical manifolds. Through the Universal Approximation 
 * Theorem, a Multi-Layer Perceptron (MLP) can seamlessly approximate ANY 
 * continuous structured function.
 *
 * THE GOLDBACH FEATURE VECTOR (CRT TENSOR):
 * We translate each prime P_i into a continuous tensor array by calculating 
 * its explicit Chinese Remainder Theorem (CRT) fingerprints across the 
 * first K sub-primes: X[i] = P_i % p_k.
 * Target Y = 1 if (2N - P_i) is Prime (Goldbach Pair). Y = 0 otherwise.
 *
 * BACKPROPAGATION LOSS GRADIENTS:
 * We iteratively execute Non-Linear Gradient Descent (Backprop) across 
 * hidden layer matrices. 
 * If Goldbach combinations inherently possess deep Algebraic topology, 
 * the network's continuous loss gradients will explicitly 'discover' the 
 * invariant mapping, driving Test Accuracy astronomically high (>80%).
 * 
 * If Combinatorial Primes operate as perfect, unstructured Mathematical Stochasticity, 
 * the target array explicitly behaves as NP-hard Pseudorandom Noise. The 
 * loss derivatives will systematically diverge, causing the Neural Network to 
 * perfectly converge on exactly the same abysmal Test Loss generated by entirely 
 * random uniform coin-flips (~50% Accuracy floor).
 *
 * This bridges rigorous Analytic Number Theory definitively with Machine Learning.
 *
 * BUILD: cc -O3 -o crack67 crack67_machine_learning.c -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_N 2000000
static char sieve[MAX_N];
static int primes[MAX_N];
static int nprimes = 0;

void init() {
    memset(sieve, 0, sizeof(sieve));
    sieve[0] = sieve[1] = 1;
    for (int i=2; i*i < MAX_N; i++)
        if (.sieve[i]) 
            for (int j=i*i; j < MAX_N; j+=i) sieve[j] = 1;
    
    for (int i=2; i < MAX_N; i++)
        if (.sieve[i]) primes[nprimes++] = i;
}

double sigmoid(double x) {
    return 1.0 / (1.0 + exp(-x));
}

double sigmoid_derivative(double x) {
    double s = sigmoid(x);
    return s * (1.0 - s);
}

// Random weight initialization: He/Glorot Uniform
double rand_weight() {
    return ((double)rand() / RAND_MAX) * 2.0 - 1.0;
}

int main() {
    init();

    printf("====================================================\n");
    printf("  CRACK 67: Machine Learning (DNN Gradient Convergence)\n");
    printf("====================================================\n\n");

    int target = 1000000;
    
    int num_valid_primes = 0;
    for (int i=0; i<nprimes; i++) {
        if (primes[i] <= target / 2) num_valid_primes++;
        else break;
    }

    int N_DATA = num_valid_primes;
    int INPUT_DIMS = 20; // First 20 primes for CRT mapping
    int HIDDEN_DIMS = 40;

    printf("  Target 2N = %d (Dataset Size: %d Prime Vectors)\n", target, N_DATA);
    printf("  DNN Architecture: Linear(%d) -> Tanh -> Linear(%d) -> Sigmoid Output\n\n", INPUT_DIMS, HIDDEN_DIMS);

    double **X = malloc(N_DATA * sizeof(double*));
    int *Y_gb = malloc(N_DATA * sizeof(int));
    int *Y_rand = malloc(N_DATA * sizeof(int));
    
    int gb_hits = 0;
    for (int i=0; i<N_DATA; i++) {
        X[i] = malloc(INPUT_DIMS * sizeof(double));
        int p = primes[i];
        for (int k=0; k<INPUT_DIMS; k++) {
            X[i][k] = (double)(p % primes[k]) / (double)primes[k]; // Normalized
        }
        
        if (.sieve[target - p]) {
            Y_gb[i] = 1;
            gb_hits++;
        } else {
            Y_gb[i] = 0;
        }
    }
    
    // Identical Density Random Targets
    for(int i=0; i<gb_hits; i++) Y_rand[i] = 1;
    for(int i=gb_hits; i<N_DATA; i++) Y_rand[i] = 0;
    srand(12345);
    for (int i = N_DATA - 1; i > 0; i--) {
        int j = rand() % (i + 1);
        int temp = Y_rand[i];
        Y_rand[i] = Y_rand[j];
        Y_rand[j] = temp;
    }

    double pos_ratio = (double)gb_hits / N_DATA;
    printf("  Target Boolean Signal Density: %.4f%%\n", pos_ratio * 100.0);

    // Train/Test Split (80/20)
    int TRAIN_N = (int)(N_DATA * 0.8);
    int TEST_N = N_DATA - TRAIN_N;

    // We will train TWO parallel identical networks (Goldbach vs Random Target)
    double W1_gb[INPUT_DIMS][HIDDEN_DIMS];
    double b1_gb[HIDDEN_DIMS];
    double W2_gb[HIDDEN_DIMS];
    double b2_gb = 0;

    double W1_rand[INPUT_DIMS][HIDDEN_DIMS];
    double b1_rand[HIDDEN_DIMS];
    double W2_rand[HIDDEN_DIMS];
    double b2_rand = 0;

    for (int h=0; h<HIDDEN_DIMS; h++) {
        for (int i=0; i<INPUT_DIMS; i++) {
            double w = rand_weight();
            W1_gb[i][h] = w;
            W1_rand[i][h] = w;
        }
        double b = rand_weight();
        b1_gb[h] = b;
        b1_rand[h] = b;
        
        double w2 = rand_weight();
        W2_gb[h] = w2;
        W2_rand[h] = w2;
    }

    double lr = 0.05;
    int epochs = 50;
    
    printf("  Executing Backpropagation (LR=%.2f, Epochs=%d)...\n", lr, epochs);

    for (int ep = 0; ep < epochs; ep++) {
        for (int i = 0; i < TRAIN_N; i++) {
            // Forward pass (GB)
            double h_out_gb[HIDDEN_DIMS];
            for (int h=0; h<HIDDEN_DIMS; h++) {
                double z = b1_gb[h];
                for (int in=0; in<INPUT_DIMS; in++) z += X[i][in] * W1_gb[in][h];
                h_out_gb[h] = tanh(z);
            }
            double out_z_gb = b2_gb;
            for (int h=0; h<HIDDEN_DIMS; h++) out_z_gb += h_out_gb[h] * W2_gb[h];
            double pred_gb = sigmoid(out_z_gb);
            
            // Backprop (GB)
            double error_gb = pred_gb - Y_gb[i];
            double d_out_gb = error_gb * sigmoid_derivative(out_z_gb);
            
            double d_h_gb[HIDDEN_DIMS];
            for (int h=0; h<HIDDEN_DIMS; h++) {
                d_h_gb[h] = d_out_gb * W2_gb[h] * (1.0 - h_out_gb[h]*h_out_gb[h]); // tanh deriv
                
                // Update W2 and b2
                W2_gb[h] -= lr * d_out_gb * h_out_gb[h];
            }
            b2_gb -= lr * d_out_gb;
            
            for (int h=0; h<HIDDEN_DIMS; h++) {
                for (int in=0; in<INPUT_DIMS; in++) {
                    W1_gb[in][h] -= lr * d_h_gb[h] * X[i][in];
                }
                b1_gb[h] -= lr * d_h_gb[h];
            }

            // Forward pass (Rand)
            double h_out_rand[HIDDEN_DIMS];
            for (int h=0; h<HIDDEN_DIMS; h++) {
                double z = b1_rand[h];
                for (int in=0; in<INPUT_DIMS; in++) z += X[i][in] * W1_rand[in][h];
                h_out_rand[h] = tanh(z);
            }
            double out_z_rand = b2_rand;
            for (int h=0; h<HIDDEN_DIMS; h++) out_z_rand += h_out_rand[h] * W2_rand[h];
            double pred_rand = sigmoid(out_z_rand);
            
            // Backprop (Rand)
            double error_rand = pred_rand - Y_rand[i];
            double d_out_rand = error_rand * sigmoid_derivative(out_z_rand);
            
            double d_h_rand[HIDDEN_DIMS];
            for (int h=0; h<HIDDEN_DIMS; h++) {
                d_h_rand[h] = d_out_rand * W2_rand[h] * (1.0 - h_out_rand[h]*h_out_rand[h]);
                W2_rand[h] -= lr * d_out_rand * h_out_rand[h];
            }
            b2_rand -= lr * d_out_rand;
            
            for (int h=0; h<HIDDEN_DIMS; h++) {
                for (int in=0; in<INPUT_DIMS; in++) {
                    W1_rand[in][h] -= lr * d_h_rand[h] * X[i][in];
                }
                b1_rand[h] -= lr * d_h_rand[h];
            }
        }
    }

    // Evaluate Test Sets
    int correct_gb = 0, correct_rand = 0;
    double loss_gb = 0, loss_rand = 0;
    
    for (int i = TRAIN_N; i < N_DATA; i++) {
        // Forward GB
        double h_out_gb[HIDDEN_DIMS];
        for (int h=0; h<HIDDEN_DIMS; h++) {
            double z = b1_gb[h];
            for (int in=0; in<INPUT_DIMS; in++) z += X[i][in] * W1_gb[in][h];
            h_out_gb[h] = tanh(z);
        }
        double out_z_gb = b2_gb;
        for (int h=0; h<HIDDEN_DIMS; h++) out_z_gb += h_out_gb[h] * W2_gb[h];
        double pred_gb = sigmoid(out_z_gb);
        
        if (pred_gb >= 0.5 && Y_gb[i] == 1) correct_gb++;
        if (pred_gb < 0.5 && Y_gb[i] == 0) correct_gb++;
        loss_gb += -Y_gb[i]*log(pred_gb + 1e-9) - (1-Y_gb[i])*log(1-pred_gb + 1e-9);

        // Forward Rand
        double h_out_rand[HIDDEN_DIMS];
        for (int h=0; h<HIDDEN_DIMS; h++) {
            double z = b1_rand[h];
            for (int in=0; in<INPUT_DIMS; in++) z += X[i][in] * W1_rand[in][h];
            h_out_rand[h] = tanh(z);
        }
        double out_z_rand = b2_rand;
        for (int h=0; h<HIDDEN_DIMS; h++) out_z_rand += h_out_rand[h] * W2_rand[h];
        double pred_rand = sigmoid(out_z_rand);
        
        if (pred_rand >= 0.5 && Y_rand[i] == 1) correct_rand++;
        if (pred_rand < 0.5 && Y_rand[i] == 0) correct_rand++;
        loss_rand += -Y_rand[i]*log(pred_rand + 1e-9) - (1-Y_rand[i])*log(1-pred_rand + 1e-9);
    }
    
    double acc_gb = (double)correct_gb / TEST_N * 100.0;
    double acc_rand = (double)correct_rand / TEST_N * 100.0;
    loss_gb /= TEST_N;
    loss_rand /= TEST_N;
    
    // Theoretical trivial baseline (predict majority class everything)
    double majority_acc = (1.0 - pos_ratio) * 100.0;
    if (pos_ratio > 0.5) majority_acc = pos_ratio * 100.0;

    printf("\n  %16s | %18s | %18s \n", "Network Metric", "Goldbach (Test)", "Random Noise (Test)");
    printf("  ----------------------------------------------------------------\n");
    printf("  %16s | %17.2f%% | %17.2f%% \n", "Accuracy (Test)", acc_gb, acc_rand);
    printf("  %16s | %18.4f | %18.4f \n", "BCE Loss (Test)", loss_gb, loss_rand);
    
    double variance = fabs(acc_gb - acc_rand); // Absolute percent diff

    printf("\n   MACHINE LEARNING VERDICT \n");
    printf("  Gradient Accuracy Divergence Variance: %.2f%%\n", variance);
    printf("  Theoretical Trivial Majority Guess Boundary: %.2f%%\n\n", majority_acc);

    if (acc_gb > majority_acc + 5.0 && acc_gb > acc_rand + 5.0) {
        printf("  RESULT: ANOMALY DETECTED. The Neural Gradients explicitly converged.\n");
        printf("  The Multi-Layer Perceptron chemically isolated the hidden Algebraic\n");
        printf("  manifold. It structurally decoupled Prime properties from formal noise.\n");
        printf("  Additive Prime combinations formally encode geometrically resolvable backdoors. ️\n");
    } else {
        printf("  RESULT: HYPOTHESIS FALSIFIED. Neural Network Gradients mathematically diverged into triviality.\n");
        printf("  Because the loss derivatives completely failed to discover any topological\n");
        printf("  mapping, the MLP structurally degenerated to pure majority probability matching.\n");
        printf("  The geometric combinatorial space of Primes is structurally encrypted,\n");
        printf("  fundamentally indistinguishable from perfectly chaotic Boolean uniform randomness. ️\n");
    }

    for (int i=0; i<N_DATA; i++) free(X[i]);
    free(X); free(Y_gb); free(Y_rand);
    return 0;
}
