import erdos265_main
import sylvester_sum_irrational
import dual_constraint_collapse
import universal_balance
import subgreedy_bounds
import subgreedy_asymptotics
import absolute_upper_bound

#print axioms greedy_erdos265_impossible
#print axioms sylvester_sum_irrational
#print axioms inductive_collapse
#print axioms universal_balance_contradiction
#print axioms coupling_pure_recurrence
#print axioms subgreedy_quadratic_growth
#print axioms product_ratio_converges
#print axioms sequence_absolute_upper_bound
