use perqed_core::program_search::ProgramInvariantSearch;

#[test]
fn test_red_to_green_oeis_sequence_matching() {
    let searcher = ProgramInvariantSearch::new();

    // 1. Red Phase: Non-matching random sequence -> Empty matches
    let random_terms = vec![7, 19, 103, 442, 901];
    let red_matches = searcher.match_sequence(&random_terms);
    assert!(red_matches.is_empty(), "Random sequence should not match OEIS database!");

    // 2. Green Phase: Exact Fibonacci slice -> Matches A000045
    let fib_slice = vec![1, 2, 3, 5, 8, 13, 21];
    let fib_matches = searcher.match_sequence(&fib_slice);
    assert_eq!(fib_matches.len(), 1);
    assert_eq!(fib_matches[0].0.id, "A000045");
    assert_eq!(fib_matches[0].0.name, "Fibonacci numbers");

    // 3. Green Phase: Exact Catalan slice -> Matches A000108
    let catalan_slice = vec![2, 5, 14, 42, 132];
    let cat_matches = searcher.match_sequence(&catalan_slice);
    assert_eq!(cat_matches.len(), 1);
    assert_eq!(cat_matches[0].0.id, "A000108");
}

#[test]
fn test_red_to_green_extremal_bounds_synthesis() {
    let searcher = ProgramInvariantSearch::new();

    // Data points generated by y = n^2
    let quadratic_data: Vec<(i64, f64)> = (1..=10).map(|n| (n, (n * n) as f64)).collect();

    let bounds = searcher.synthesize_extremal_bounds(&quadratic_data);
    assert!(!bounds.is_empty());

    // Verify candidate bounds contain O(n^2) bound
    let quad_bound = bounds.iter().find(|b| b.asymptotic_class == "O(n^2)");
    assert!(quad_bound.is_some());
    let b = quad_bound.unwrap();
    assert_eq!(b.expression, "1 * (n * n)");
}
