// Removed `node:vm` for Bun 1.3 stability

/**
 * calculate_degrees_of_freedom
 * 
 * Takes an algebraic edge rule generated by the ARCHITECT (as a Javascript
 * function body string) and evaluates it over all unique pairs of vertices (i < j).
 * It hashes or records the exact string sets or outcomes to determine how many 
 * independent variables (degrees of freedom) the symmetry forces.
 * 
 * e.g., A complete random graph on N vertices has N(N-1)/2 degrees of freedom.
 * But a Circulant graph on N vertices only has floor(N/2) degrees of freedom.
 * 
 * Returns a statement indicating the exact dimension of the search space $2^N$.
 */
import { compileEdgeRule } from "../search/algebraic_builder";

export function calculate_degrees_of_freedom(edge_rule_js: string, vertices: number): string {
  let ruleFn: (i: number, j: number) => any;
  try {
    ruleFn = compileEdgeRule(edge_rule_js);
  } catch (err: any) {
    return `SandboxError: failed to compile edge_rule_js — ${err.message}`;
  }

  const uniqueVars = new Set<string>();

  for (let i = 0; i < vertices; i++) {
    for (let j = i + 1; j < vertices; j++) {
      try {
        const val = ruleFn(i, j);
        uniqueVars.add(String(val));
      } catch (err: any) {
        return `SandboxError: rule threw at (i=${i}, j=${j}) — ${err.message}`;
      }
    }
  }

  const N = uniqueVars.size;
  return `This symmetry yields ${N} independent variables. Space size: 2^{${N}}.`;
}

/**
 * query_known_graphs
 * 
 * Returns the mathematical symmetry type of known smaller Ramsey bounds if 
 * available in our knowledge base.
 */
export function query_known_graphs(r: number, s: number): string {
  if (r === 3 && s === 3) return "R(3,3)=6. Lower bound 5 is a pentagon (Cayley graph over Z_5 with {1, 4}).";
  if (r === 3 && s === 4) return "R(3,4)=9. Lower bound 8 is a cubic graph with twisted edges (Paley graph of order 9 is close context).";
  if (r === 3 && s === 5) return "R(3,5)=14. Lower bound 13 is a Paley graph of order 13. Edges connect if diff is a quadratic residue modulo 13: {1, 3, 4, 9, 10, 12}.";
  if (r === 4 && s === 4) return "R(4,4)=18. Lower bound 17 is the Paley graph of order 17. Circulant with quadratic residues modulo 17.";
  if (r === 4 && s === 5) return "R(4,5)=25. Lower bound 24 is a circulant graph on Z_24, or a Paley-like graph. But R(4,5) is fully solved at 25.";
  if (r === 4 && s === 6) return "R(4,6) is known to be >= 36. Often constructed using quadratic or cubic residues on Z_35, or a block design.";
  return `No specific canonical graph symmetry is cached for R(${r},${s}). Attempt a Circulant graph, a Paley graph, or a cyclic block design.`;
}

export async function query_literature(search_term: string): Promise<string> {
  let libraryContext = `Literature search for "${search_term}":\n`;
  try {
    const { LocalEmbedder } = await import("../embeddings/embedder");
    const { VectorDatabase } = await import("../embeddings/vector_store");
    const embedder = new LocalEmbedder();
    const db = new VectorDatabase();
    await db.initialize();

    const queryVector = await embedder.embed(search_term);
    if (queryVector.length > 0) {
      const matches = await db.search(queryVector, 3);
      if (matches.length > 0) {
        matches.forEach((m: any, i: number) => {
          libraryContext += `${i + 1}. **${m.theoremSignature}**\n   ${m.successfulTactic}\n\n`;
        });
        return libraryContext;
      }
    }
    return `No empirical records or theorems found specifically matching "${search_term}".`;
  } catch (e: any) {
    return `Failed to query literature database: ${e.message}`;
  }
}

