/**
 * Lean Codegen — Generate Lean 4 proof from a Ramsey witness.
 *
 * Takes an adjacency matrix and produces a self-contained Lean file
 * that proves the Ramsey lower bound via `decide`.
 */

/**
 * Generate a complete Lean 4 proof file for a Ramsey lower bound.
 *
 * @param theoremName - Valid Lean identifier for the theorem
 * @param n - Number of vertices
 * @param r - Clique size (red)
 * @param s - Independent set size (blue)
 * @param witness - n×n adjacency matrix (boolean)
 * @returns Complete Lean 4 source code
 */
export function generateRamseyLean(
  theoremName: string,
  n: number,
  r: number,
  s: number,
  witness: boolean[][],
): string {
  // Build the adjacency lookup table
  const rows: string[] = [];
  for (let i = 0; i < n; i++) {
    const entries: string[] = [];
    for (let j = 0; j < n; j++) {
      entries.push(witness[i]![j]! ? "true" : "false");
    }
    rows.push(`    | ${i} => match j with\n` +
      entries.map((e, j) => `      | ${j} => ${e}`).join("\n"));
  }

  // Build the Lean source
  const lines = [
    `/-`,
    `  Generated by Perqed — Ramsey lower bound witness`,
    `  R(${r}, ${s}) ≥ ${n + 1} (${n}-vertex witness)`,
    `-/`,
    ``,
    `set_option maxHeartbeats 800000000`,
    ``,
    `/-- The adjacency function for the R(${r},${s}) witness on ${n} vertices. -/`,
    `def ${theoremName}_adj (i j : Fin ${n}) : Bool :=`,
    `  match i with`,
    ...rows.map(r => r),
    ``,
    `/-- Every subset of ${r} vertices has at least one non-edge. -/`,
    `private def no_red_K${r} : Bool :=`,
    `  Id.run do`,
    `    let mut ok := true`,
    ...generateCliqueCheck(n, r, `${theoremName}_adj`),
    `    ok`,
    ``,
    `/-- Every subset of ${s} vertices has at least one edge. -/`,
    `private def no_blue_K${s} : Bool :=`,
    `  Id.run do`,
    `    let mut ok := true`,
    ...generateIndSetCheck(n, s, `${theoremName}_adj`),
    `    ok`,
    ``,
    `/-- Main theorem: the graph witnesses R(${r},${s}) ≥ ${n + 1}. -/`,
    `theorem ${theoremName} : no_red_K${r} = true ∧ no_blue_K${s} = true := by decide`,
    ``,
  ];

  return lines.join("\n");
}

/** Generate nested loops checking all C(n,r) subsets for cliques */
function generateCliqueCheck(n: number, r: number, adjName: string): string[] {
  // Generate r nested for-loops
  const vars = Array.from({ length: r }, (_, i) => `v${i}`);
  const lines: string[] = [];
  const indent = "    ";

  for (let d = 0; d < r; d++) {
    const pad = indent + "  ".repeat(d);
    const lo = d === 0 ? "0" : `${vars[d - 1]} + 1`;
    lines.push(`${pad}for ${vars[d]} in [${lo}:${n}] do`);
  }

  // Inner check: all pairs have edges → found a clique → ok = false
  const pad = indent + "  ".repeat(r);
  const checks: string[] = [];
  for (let i = 0; i < r; i++) {
    for (let j = i + 1; j < r; j++) {
      checks.push(`${adjName} ⟨${vars[i]}, by omega⟩ ⟨${vars[j]}, by omega⟩`);
    }
  }
  lines.push(`${pad}if ${checks.join(" && ")} then`);
  lines.push(`${pad}  ok := false`);

  return lines;
}

/** Generate nested loops checking all C(n,s) subsets for independent sets */
function generateIndSetCheck(n: number, s: number, adjName: string): string[] {
  const vars = Array.from({ length: s }, (_, i) => `v${i}`);
  const lines: string[] = [];
  const indent = "    ";

  for (let d = 0; d < s; d++) {
    const pad = indent + "  ".repeat(d);
    const lo = d === 0 ? "0" : `${vars[d - 1]} + 1`;
    lines.push(`${pad}for ${vars[d]} in [${lo}:${n}] do`);
  }

  const pad = indent + "  ".repeat(s);
  const checks: string[] = [];
  for (let i = 0; i < s; i++) {
    for (let j = i + 1; j < s; j++) {
      checks.push(`!${adjName} ⟨${vars[i]}, by omega⟩ ⟨${vars[j]}, by omega⟩`);
    }
  }
  lines.push(`${pad}if ${checks.join(" && ")} then`);
  lines.push(`${pad}  ok := false`);

  return lines;
}
