/**
 * Lean Codegen — Generate Lean 4 proof from a Ramsey witness.
 *
 * Takes an adjacency matrix and produces a self-contained Lean file
 * that proves the Ramsey lower bound via `native_decide`.
 *
 * Strategy: define the adjacency as a decidable function, then state
 * the properties directly and verify with `native_decide`.
 */

/**
 * Generate a complete Lean 4 proof file for a Ramsey lower bound.
 */
export function generateRamseyLean(
  theoremName: string,
  n: number,
  r: number,
  s: number,
  witness: boolean[][],
): string {
  // Build the adjacency lookup as a decision list
  const cases: string[] = [];
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      if (witness[i]![j]!) {
        cases.push(`  | ${i}, ${j} => true`);
        cases.push(`  | ${j}, ${i} => true`);
      }
    }
  }

  const lines = [
    `/-`,
    `  Generated by Perqed — Ramsey lower bound witness`,
    `  R(${r}, ${s}) ≥ ${n + 1} (${n}-vertex witness)`,
    `-/`,
    ``,
    `set_option maxHeartbeats 800000000`,
    ``,
    `/-- Adjacency function for the R(${r},${s}) witness on ${n} vertices. -/`,
    `def ${theoremName}_adj : Fin ${n} → Fin ${n} → Bool`,
    ...cases,
    `  | _, _ => false`,
    ``,
    `/-- No subset of ${r} vertices forms a clique (all edges present). -/`,
    `def ${theoremName}_noK${r} : Bool :=`,
    ...generateDecidableCheck(n, r, `${theoremName}_adj`, true),
    ``,
    `/-- No subset of ${s} vertices forms an independent set (no edges). -/`,
    `def ${theoremName}_noI${s} : Bool :=`,
    ...generateDecidableCheck(n, s, `${theoremName}_adj`, false),
    ``,
    `theorem ${theoremName} : ${theoremName}_noK${r} = true ∧ ${theoremName}_noI${s} = true := by native_decide`,
    ``,
  ];

  return lines.join("\n");
}

/**
 * Generate a decidable check that iterates over all C(n,k) subsets.
 *
 * For cliques (wantEdge=true): checks that no k-subset has all edges present.
 * For independent sets (wantEdge=false): checks that no k-subset has all edges absent.
 *
 * Uses nested List.all over Fin values — fully decidable.
 */
function generateDecidableCheck(
  n: number,
  k: number,
  adjName: string,
  wantEdge: boolean,
): string[] {
  // Build a decidable expression using nested Fin.foldr or List operations
  // Strategy: unfold into a direct boolean computation using Fin.val comparisons
  const vars = Array.from({ length: k }, (_, i) => `v${i}`);

  // Build nested "decide"-friendly iteration using List.range
  const lines: string[] = [];
  lines.push(`  let fins : List (Fin ${n}) := List.finRange ${n}`);

  // Generate nested filter + check
  lines.push(`  fins.all fun ${vars[0]} =>`);
  for (let d = 1; d < k; d++) {
    const indent = "    ".repeat(d);
    lines.push(`${indent}fins.all fun ${vars[d]} =>`);
  }

  // Guard: strictly increasing indices
  const guards: string[] = [];
  for (let i = 0; i < k - 1; i++) {
    guards.push(`${vars[i]}.val < ${vars[i + 1]!}.val`);
  }

  // Edge checks
  const edgeChecks: string[] = [];
  for (let i = 0; i < k; i++) {
    for (let j = i + 1; j < k; j++) {
      if (wantEdge) {
        edgeChecks.push(`${adjName} ${vars[i]} ${vars[j]}`);
      } else {
        edgeChecks.push(`!${adjName} ${vars[i]} ${vars[j]}`);
      }
    }
  }

  const guardExpr = guards.join(" && ");
  const checkExpr = edgeChecks.join(" && ");
  const innerIndent = "    ".repeat(k);

  // If guard is met and all edges match → this is a bad subset → false
  // Otherwise → true
  lines.push(`${innerIndent}if ${guardExpr} then`);
  lines.push(`${innerIndent}  !(${checkExpr})`);
  lines.push(`${innerIndent}else`);
  lines.push(`${innerIndent}  true`);

  return lines;
}
