/**
 * formalist_extension.ts — Lean 4 lemma emitter for detected obstructions.
 *
 * Takes a detected obstruction subgraph, formats its edge list into a Lean 4
 * definition block, and writes it to the run's scratch directory. Optionally
 * calls ScribeAgent to polish the sorry-stub into a more structured skeleton.
 */
import { AdjacencyMatrix } from "../math/graph/AdjacencyMatrix";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

export interface ObstructionLemmaResult {
  /** Path to the generated .lean file */
  leanPath: string;
  /** The raw Lean 4 source text */
  leanSource: string;
  /** Short label for the obstruction (e.g. "Obstruction_Type_A") */
  label: string;
}

/**
 * Emit a Lean 4 definition and sorry-stubbed theorem for the given obstruction.
 *
 * The generated file follows the pattern:
 *
 *   import Mathlib.Combinatorics.SimpleGraph.Basic
 *
 *   def Obstruction_<runName> : Finset (Fin 35 × Fin 35) :=
 *     {(0, 3), (1, 7), ...}
 *
 *   theorem no_witness_contains_obstruction_<runName>
 *       (g : SimpleGraph (Fin 35))
 *       (h : Obstruction_<runName> ⊆ g.edgeSet) :
 *       ¬ IsValidWitness g := by
 *     sorry
 *
 * @param obstruction  The common subgraph detected by extractCommonSubgraph
 * @param runName      Unique run id, used for naming the Lean definition
 * @param scratchDir   Directory to write the .lean file into
 */
export async function emitObstructionLemma(
  obstruction: AdjacencyMatrix,
  runName: string,
  scratchDir: string = `agent_workspace/runs/${runName}/scratch`
): Promise<ObstructionLemmaResult> {
  await mkdir(scratchDir, { recursive: true });

  const label = `Obstruction_${runName.replace(/[^a-zA-Z0-9]/g, "_")}`;
  const leanPath = join(scratchDir, "obstruction.lean");

  // Build edge set literal
  const edges: string[] = [];
  const n = obstruction.n;
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      if (obstruction.hasEdge(i, j)) {
        edges.push(`(${i}, ${j})`);
      }
    }
  }

  const edgeSetLiteral = edges.length > 0
    ? `{${edges.join(", ")}}`
    : "{}";

  const leanSource = [
    `-- Auto-generated by Perqed FormalistExtension`,
    `-- Run: ${runName}  |  Obstruction: ${edges.length} invariant edges on ${n} vertices`,
    `-- This file requires Mathlib for SimpleGraph definitions.`,
    ``,
    `import Mathlib.Combinatorics.SimpleGraph.Basic`,
    ``,
    `open SimpleGraph`,
    ``,
    `/-- The shared topological obstruction detected across near-miss search attempts. -/`,
    `def ${label} : Finset (Fin ${n} × Fin ${n}) :=`,
    `  ${edgeSetLiteral}`,
    ``,
    `/-- No valid Ramsey witness can contain this obstruction as a substructure. -/`,
    `theorem no_witness_contains_${label}`,
    `    (g : SimpleGraph (Fin ${n}))`,
    `    (h : ∀ e ∈ ${label}, e ∈ g.edgeSet) :`,
    `    ¬ IsValidWitness g := by`,
    `  -- TODO: Replace with Tactician spray or manual proof`,
    `  sorry`,
    ``,
  ].join("\n");

  await Bun.write(leanPath, leanSource);

  return { leanPath, leanSource, label };
}
