/**
 * Sprint 21: CycleFinder — Bounded DFS for Power-of-2 Cycles
 *
 * Checks whether a graph (as an adjacency list) contains a simple cycle
 * whose length is a power of 2: specifically 4, 8, or 16.
 *
 * Used by the General Solver pipeline to verify the Erdős-Gyárfás conjecture
 * on concrete graphs generated by nauty/geng.
 */

export class CycleFinder {
  private static readonly TARGET_LENGTHS = new Set([4, 8, 16]);
  private static readonly MAX_LEN = 16;

  /**
   * Returns true if the graph contains a simple cycle of length 4, 8, or 16.
   */
  static hasPowerOfTwoCycle(adj: number[][]): boolean {
    const n = adj.length;
    if (n < 4) return false;

    for (let startNode = 0; startNode < n; startNode++) {
      // Optimization: mark lower-index nodes as visited to avoid
      // finding the same cycle from multiple starting vertices
      const visited = new Set<number>();
      for (let i = 0; i < startNode; i++) visited.add(i);

      if (this.dfs(adj, startNode, startNode, 1, visited)) {
        return true;
      }
    }
    return false;
  }

  private static dfs(
    adj: number[][],
    startNode: number,
    currentNode: number,
    depth: number,
    visited: Set<number>,
  ): boolean {
    // At a target depth, check if we can close the cycle
    if (this.TARGET_LENGTHS.has(depth)) {
      if (adj[currentNode]!.includes(startNode)) {
        return true;
      }
    }

    // Don't explore beyond max cycle length
    if (depth >= this.MAX_LEN) return false;

    visited.add(currentNode);

    for (const neighbor of adj[currentNode]!) {
      if (!visited.has(neighbor)) {
        if (this.dfs(adj, startNode, neighbor, depth + 1, visited)) {
          return true;
        }
      }
    }

    visited.delete(currentNode);
    return false;
  }
}
