//! Core Domain Types for Perqed v2

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Structured mathematical conjecture definition
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Conjecture {
    pub conjecture_id: String,
    pub domain: String,
    pub informal_claim: String,
    pub hypotheses: Vec<String>,
    pub target: String,
    #[serde(default)]
    pub variables: HashMap<String, String>,
    #[serde(default)]
    pub custom_predicates: Vec<crate::falsification::PredicateSpec>,
    #[serde(default)]
    pub provenance_source: Option<String>,
}

/// Parsed mathematical statement from LaTeX / TeX AST
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParsedTheorem {
    pub label: String,
    pub env_type: String, // "theorem", "lemma", "proposition", "corollary"
    pub raw_latex: String,
    pub informal_claim: String,
    pub hypotheses: Vec<String>,
    pub conclusion: String,
    pub source_file: String,
}

/// Tactic candidate generated by formal provers
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TacticCandidate {
    pub tactic_code: String,
    pub score: f64,
    pub generator_model: String,
    #[serde(default)]
    pub is_terminal: bool,
}

/// Proof State representation for MCTS search
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProofState {
    pub open_goals: Vec<String>,
    pub hypotheses: Vec<String>,
    pub is_solved: bool,
    pub cumulative_tactics: Vec<String>,
    pub search_depth: usize,
    pub raw_lean_state: String,
}

/// Configuration parameters for MCTS proof search
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MctsConfig {
    pub max_iterations: usize,
    pub max_depth: usize,
    pub exploration_c: f64,
    pub num_candidates_per_step: usize,
    pub sublemma_depth_threshold: usize,
    pub timeout_seconds: u64,
}

impl Default for MctsConfig {
    fn default() -> Self {
        Self {
            max_iterations: 60,
            max_depth: 12,
            exploration_c: 1.414,
            num_candidates_per_step: 5,
            sublemma_depth_threshold: 4,
            timeout_seconds: 60,
        }
    }
}

/// Audit verification summary report
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditReport {
    pub proof_declaration: String,
    pub spec_declaration: String,
    pub spec_sha256: String,
    pub lock_verified: bool,
    pub kernel_audit_passed: bool,
    pub signature_diff_passed: bool,
    pub axioms_used: Vec<String>,
    pub timestamp: DateTime<Utc>,
    pub details: String,
}

/// Formatted publication artifact draft
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicationDraft {
    pub title: String,
    pub authors: Vec<String>,
    pub abstract_text: String,
    pub latex_content: String,
    pub lean_spec_code: String,
    pub lean_proof_code: String,
    pub spec_hash: String,
    pub audit_report: AuditReport,
    pub generated_at: DateTime<Utc>,
}
