//! Core Domain Types for Perqed v2

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Structured mathematical conjecture definition
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Conjecture {
    pub conjecture_id: String,
    pub domain: String,
    pub informal_claim: String,
    pub hypotheses: Vec<String>,
    pub target: String,
    #[serde(default)]
    pub variables: HashMap<String, String>,
    #[serde(default)]
    pub custom_predicates: Vec<crate::falsification::PredicateSpec>,
    #[serde(default)]
    pub provenance_source: Option<String>,
}

/// Parsed mathematical statement from LaTeX / TeX AST
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParsedTheorem {
    pub label: String,
    pub env_type: String, // "theorem", "lemma", "proposition", "corollary"
    pub raw_latex: String,
    pub informal_claim: String,
    pub hypotheses: Vec<String>,
    pub conclusion: String,
    pub source_file: String,
}

/// Tactic candidate generated by formal provers
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TacticCandidate {
    pub tactic_code: String,
    pub score: f64,
    pub generator_model: String,
    #[serde(default)]
    pub is_terminal: bool,
}

/// Heuristic weights and scoring parameters for MCTS proof search
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MctsHeuristicWeights {
    pub depth_penalty_factor: f64,
    pub goal_reduction_base: f64,
    pub cycle_penalty_value: f64,
    pub solved_value: f64,
    pub empty_goals_value: f64,
    pub max_heuristic_value: f64,
}

impl Default for MctsHeuristicWeights {
    fn default() -> Self {
        Self {
            depth_penalty_factor: 0.05,
            goal_reduction_base: 1.0,
            cycle_penalty_value: -1.0,
            solved_value: 1.0,
            empty_goals_value: 0.9,
            max_heuristic_value: 0.95,
        }
    }
}

/// Prior probability scores for heuristic and premise candidate tactic injection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TacticPriorScores {
    pub rfl_score: f64,
    pub decision_proc_score: f64,
    pub rewrite_premise_score: f64,
    pub exact_premise_score: f64,
    pub exact_hole_premise_score: f64,
    pub apply_premise_score: f64,
    pub simp_premise_score: f64,
    pub constructor_score: f64,
    pub intro_score: f64,
}

impl Default for TacticPriorScores {
    fn default() -> Self {
        Self {
            rfl_score: 0.95,
            decision_proc_score: 0.90,
            rewrite_premise_score: 0.85,
            exact_premise_score: 0.84,
            exact_hole_premise_score: 0.83,
            apply_premise_score: 0.82,
            simp_premise_score: 0.81,
            constructor_score: 0.80,
            intro_score: 0.85,
        }
    }
}

/// Proof State representation for MCTS search
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProofState {
    pub open_goals: Vec<String>,
    pub hypotheses: Vec<String>,
    pub is_solved: bool,
    pub cumulative_tactics: Vec<String>,
    pub search_depth: usize,
    pub raw_lean_state: String,
}

/// Configuration parameters for MCTS proof search
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MctsConfig {
    pub max_iterations: usize,
    pub max_depth: usize,
    pub exploration_c: f64,
    pub num_candidates_per_step: usize,
    pub sublemma_depth_threshold: usize,
    pub timeout_seconds: u64,
    #[serde(default)]
    pub heuristics: MctsHeuristicWeights,
    #[serde(default)]
    pub premise_weights: crate::ingestion::HybridPremiseWeights,
    #[serde(default)]
    pub tactic_scores: TacticPriorScores,
}

impl Default for MctsConfig {
    fn default() -> Self {
        Self {
            max_iterations: 60,
            max_depth: 12,
            exploration_c: 1.414,
            num_candidates_per_step: 5,
            sublemma_depth_threshold: 4,
            timeout_seconds: 60,
            heuristics: MctsHeuristicWeights::default(),
            premise_weights: crate::ingestion::HybridPremiseWeights::default(),
            tactic_scores: TacticPriorScores::default(),
        }
    }
}

/// Audit verification summary report
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditReport {
    pub proof_declaration: String,
    pub spec_declaration: String,
    pub spec_sha256: String,
    pub lock_verified: bool,
    pub kernel_audit_passed: bool,
    pub signature_diff_passed: bool,
    pub axioms_used: Vec<String>,
    pub timestamp: DateTime<Utc>,
    pub details: String,
}

/// Formatted publication artifact draft
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublicationDraft {
    pub title: String,
    pub authors: Vec<String>,
    pub abstract_text: String,
    pub latex_content: String,
    pub lean_spec_code: String,
    pub lean_proof_code: String,
    pub spec_hash: String,
    pub audit_report: AuditReport,
    pub generated_at: DateTime<Utc>,
}
