import { writeFileSync, appendFileSync, existsSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import {
  computeAPEnergy,
  computeAPDelta,
  findViolatingAPs,
  repairCandidates,
  generateZ3APRepairScript,
} from "../src/search/ap_energy";
import { BridgeLearner } from "../src/search/bridge_learner";
import { TheoremGraph } from "../src/proof_dag/theorem_graph";

// ── Config ────────────────────────────────────────────────────────────────────
// Target: W(5;3) > 170  (5 colors, no monochromatic 3-AP, best known LB = 170)
// Run:    bun tools/vdw_loop.ts --start=170 --colors=5 --k=3 --iters=20000000

const args = process.argv.slice(2);
const getArg = (flag: string, def: number) => {
  const a = args.find(a => a.startsWith(`--${flag}=`));
  return a ? parseInt(a.split("=")[1]!) : def;
};
let N = getArg("start", 170);
const K = getArg("colors", 5);
const AP_K = getArg("k", 3);
const SA_ITERS = getArg("iters", 20_000_000);
const MAX_ROUNDS = getArg("rounds", 100_000);
const REPAIR_THRESHOLD = getArg("repair", 10);
const OUT_DIR = "/tmp/vdw";
if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const bridgeLearner = new BridgeLearner("/tmp/vdw_bridge_experiences.jsonl");
const theoremGraph = new TheoremGraph("/tmp/vdw_theorem_graph.jsonl");

// ── Energy (O(N²/k) full, used only for initialisation and verification) ─────

function fullEnergy(p: Int8Array): number {
  return computeAPEnergy(p, N, AP_K);
}

// ── SA core — O(N) delta per step ────────────────────────────────────────────

function runSA(
  initial: Int8Array,
  iters: number,
  T0: number = 8.0,
  alpha: number = 0.9999994,
): { partition: Int8Array; energy: number } {
  const p = new Int8Array(initial);
  let E = fullEnergy(p);       // O(N²/k) once at startup — acceptable
  let T = T0;

  for (let iter = 0; iter < iters && E > 0; iter++) {
    const pos = 1 + ((Math.random() * N) | 0);
    const old_c = p[pos]!;
    const new_c = (Math.random() * K) | 0;
    if (old_c === new_c) { T *= alpha; continue; }

    // O(N) delta — the hot path
    const dE = computeAPDelta(p, N, AP_K, pos, old_c, new_c);

    if (dE <= 0 || Math.random() < Math.exp(-dE / T)) {
      p[pos] = new_c;
      E += dE;
    }
    T *= alpha;
  }

  // Recompute exactly to guard against any floating-point accumulation drift
  const finalE = fullEnergy(p);
  return { partition: p, energy: finalE };
}


// ── Initialisation strategies ─────────────────────────────────────────────────

function initModular(): Int8Array {
  const p = new Int8Array(N + 1);
  for (let i = 1; i <= N; i++) p[i] = (i - 1) % K;
  return p;
}

/** Digital-sum base-K seed (Prouhet-Tarry-Escott-inspired). */
function initPTE(): Int8Array {
  const p = new Int8Array(N + 1);
  for (let i = 1; i <= N; i++) {
    let sum = 0, n = i;
    while (n > 0) { sum += n % K; n = Math.floor(n / K); }
    p[i] = sum % K;
  }
  return p;
}

/** Quadratic residues mod prime: color by QR class. */
function initQR(prime: number = 79): Int8Array {
  const p = new Int8Array(N + 1);
  const qrs = new Set<number>();
  for (let x = 1; x < prime; x++) qrs.add((x * x) % prime);
  for (let i = 1; i <= N; i++) {
    const r = i % prime;
    p[i] = r === 0 ? 0 : qrs.has(r) ? 1 : 2;
    p[i] = p[i]! % K; // safe for K=4
  }
  return p;
}

/** Random init. */
function initRandom(): Int8Array {
  const p = new Int8Array(N + 1);
  for (let i = 1; i <= N; i++) p[i] = Math.floor(Math.random() * K);
  return p;
}

// ── Witness emission ──────────────────────────────────────────────────────────

function emitWitness(partition: Int8Array): void {
  const colorClasses: number[][] = Array.from({ length: K }, () => []);
  for (let i = 1; i <= N; i++) colorClasses[partition[i]!]!.push(i);

  // JSON
  const jsonPath = `${OUT_DIR}/vdw_witness_N${N}.json`;
  writeFileSync(jsonPath, JSON.stringify({
    N, K, AP_K,
    lower_bound: N,
    coloring: Array.from(partition).slice(1),
    color_classes: colorClasses,
    timestamp: new Date().toISOString(),
  }, null, 2));
  console.log(`\n  💾 Witness → ${jsonPath}`);

  // Lean 4
  const lean = generateVdWLean(partition);
  const leanPath = `${OUT_DIR}/vdw_proof_N${N}.lean`;
  writeFileSync(leanPath, lean);
  console.log(`  📜 Lean 4 → ${leanPath}`);

  // Record in theorem graph
  theoremGraph.addNode({
    kind: "WITNESS",
    label: `W(${AP_K};${K}) > ${N - 1}`,
    energy: 0,
    evidence: JSON.stringify(colorClasses),
  });
}

function generateVdWLean(partition: Int8Array): string {
  const colored = Array.from(partition).slice(1, N + 1)
    .map((c, i) => `  | ${i} => ${c}`).join("\n");
  return `-- Auto-generated by Perqed vdw_loop.ts
-- Proves W(${AP_K};${K}) > ${N - 1}
-- A ${K}-coloring of {0..${N-1}} with no monochromatic ${AP_K}-term AP.

def vdwColoring${N} : Fin ${N} → Fin ${K}
${colored}
  | _ => ⟨0, by omega⟩

-- Verification (decidable): no element and common difference give a mono AP
#eval do
  let c := vdwColoring${N}
  let mut violations := 0
  for a in List.range ${N} do
    for d in List.range ${N} do
      if d == 0 then continue
      if a + ${AP_K - 1} * (d + 1) <= ${N} then
        let ap := List.range ${AP_K} |>.map (fun i => a + i * (d + 1))
        if ap.all (fun i => c ⟨i, by omega⟩ == c ⟨ap[0]!, by omega⟩) then
          violations := violations + 1
  IO.println s!"Violations: {violations}"  -- should print 0
`;
}

// ── Z3 repair ─────────────────────────────────────────────────────────────────

function tryZ3Repair(partition: Int8Array): Int8Array | null {
  const cands = repairCandidates(partition, N, AP_K);
  if (cands.size === 0 || cands.size > 200) return null;
  const script = generateZ3APRepairScript(
    partition, N, K, [...cands], AP_K
  );
  const scriptPath = "/tmp/vdw_z3_repair.py";
  writeFileSync(scriptPath, script);
  try {
    const out = execSync(`python3 ${scriptPath}`, { timeout: 60_000 }).toString();
    if (out.includes("sat") && !out.includes("unsat")) {
      const repaired = new Int8Array(partition);
      for (const line of out.split("\n")) {
        const m = line.match(/c_(\d+)=(\d+)/);
        if (m) repaired[parseInt(m[1]!)] = parseInt(m[2]!);
      }
      return repaired;
    }
  } catch { /* timeout or z3 failure */ }
  return null;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`\n${"═".repeat(60)}`);
  console.log(`  🔢 Van der Waerden SA Search`);
  console.log(`  W(${AP_K};${K}): seeking a ${K}-coloring of {1..N} with no mono ${AP_K}-AP`);
  console.log(`  Starting N=${N} | SA iters=${SA_ITERS.toLocaleString()}`);
  console.log(`${"═".repeat(60)}\n`);

  // Warm-start from prior witness if available
  let bestPartition: Int8Array | null = null;

  for (let round = 1; round <= MAX_ROUNDS; round++) {
    // Try 4 diverse seeds each round
    const seeds = [
      bestPartition ?? initPTE(),
      initQR(),
      initModular(),
      initRandom(),
    ];

    let roundBestE = Infinity;
    let roundBestP: Int8Array = seeds[0]!;

    for (const seed of seeds) {
      const { partition: result, energy: E } = runSA(seed, SA_ITERS);
      if (E < roundBestE) { roundBestE = E; roundBestP = result; }
      if (E === 0) break;
    }

    console.log(`[Round ${round}] N=${N} | E=${roundBestE}`);

    if (roundBestE === 0) {
      console.log(`\n  🎉 W(${AP_K};${K}) > ${N - 1} confirmed! Emitting witness...\n`);
      emitWitness(roundBestP);
      N++;
      bestPartition = roundBestP; // warm start for next N
      console.log(`\n  🔼 Growing to N=${N}...\n`);
      continue;
    }

    // Z3 repair if close
    if (roundBestE <= REPAIR_THRESHOLD) {
      console.log(`  🔧 Z3 repair attempt (E=${roundBestE}, ${repairCandidates(roundBestP, N, AP_K).size} candidates)...`);
      const repaired = tryZ3Repair(roundBestP);
      if (repaired !== null) {
        const repairedE = fullEnergy(repaired);
        if (repairedE === 0) {
          console.log(`\n  🎉 Z3 repair found witness! W(${AP_K};${K}) > ${N - 1}\n`);
          emitWitness(repaired);
          N++;
          bestPartition = repaired;
          continue;
        }
        console.log(`  ✨ Z3 improved: E=${roundBestE} → ${repairedE}`);
        if (repairedE < roundBestE) roundBestP = repaired;
      } else {
        console.log(`  ❌ Z3: unsat`);
        theoremGraph.addNode({
          kind: "OBSTRUCTION",
          label: `Z3 UNSAT N=${N} E=${roundBestE}`,
          energy: roundBestE,
          evidence: "",
        });
      }
    }

    // BridgeLearner every 5 rounds
    if (round % 5 === 0 && roundBestE <= REPAIR_THRESHOLD) {
      const candidates = bridgeLearner.propose().slice(0, 2);
      for (const cand of candidates) {
        const result = await bridgeLearner.evaluate(cand, roundBestP, N, K, 300);
        bridgeLearner.updateRewardModel(cand, result);
        if (result.discreteEAfter < roundBestE) {
          console.log(`  🔬 [Bridge:${cand.manifold}] E ${result.discreteEBefore} → ${result.discreteEAfter}`);
        }
      }
    }

    bestPartition = roundBestP;
  }

  console.log(`\n  ⏱️  ${MAX_ROUNDS} rounds complete at N=${N}. No witness for current N.`);
}

main().catch(console.error);
